routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\LoginController@view');
Route::get('/logout', 'User\LoginController@logout');
Route::get('dashboard', 'DashboardController@view');
Route::get('forms', 'FormsController@view');

Route::group(['prefix' => 'form-d'], function(){
    Route::get('', 'FormDController@list');
    Route::get('create', 'FormDController@create');
    Route::get('{uuid}/edit', 'FormDController@edit');
    Route::get('{uuid}', 'FormDController@view');
    Route::get('{uuid}/form-f', 'FormFController@create');
    Route::get('{uuid}/form-f/view', 'FormFController@view');

});

Route::group(['prefix' => 'form-ii'], function(){
    Route::get('', 'FormIIController@list');
    Route::get('create', 'FormIIController@create');
    Route::get('{uuid}/edit', 'FormIIController@edit');
    Route::get('{uuid}', 'FormIIController@view');
    Route::get('{uuid}/form-iii', 'FormIIIController@create');
    Route::get('{uuid}/form-iii/view', 'FormIIIController@view');

});

Route::group(['prefix' => 'form-a1'], function(){
    Route::get('', 'FormA1Controller@list');
    Route::get('create', 'FormA1Controller@create');
    Route::get('{uuid}/edit', 'FormA1Controller@edit');
    Route::get('{uuid}', 'FormA1Controller@view');
    Route::get('{uuid}/form-a2', 'FormA2Controller@create');
    Route::get('{uuid}/form-a2/view', 'FormA2Controller@view');

});

app/Models/Forms/FormA1.php
<?php

namespace App\Models\Forms;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormA1 extends Model
{
    use SoftDeletes;

    protected $table = 'form_a1';

    protected $fillable = [];

    protected $hidden = ['id', 'created_at', 'updated_at', 'deleted_at', 'created_by', 'updated_by', 'deleted_by'];
    
    protected $casts = ['documents' => 'object', 'edit_required' => 'boolean'];

    public function forma2(){
        return $this->hasOne('App\Models\Forms\FormA2', 'id', 'form_a2_id');
    }



    public function getCanViewAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if($this->created_by === $user->id){
            return true;
        }
        if($user->can_process_form_a1){
            return true;
        }
        return false;
    }

    public function getCanEditAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if(!$this->edit_required){
            return false;
        }

        return $this->created_by  === $user->id;
    }



   
    public function owner(){
        return $this->hasOne('App\Models\User', 'id', 'created_by');
    }

    public function process(){
        return $this->hasOne('App\Models\Forms\FormA1Process', 'form_a1_id', 'id')->orderBy('id', 'desc');
    }

    public function getCanProcessAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if(!$user->can_process_form_a1){
            return false;
        }
        if($this->can_edit){
            return false;
        }
        if($this->form_a2_id){
            return false;
        }
        if($user->is_ao && !$this->process->verified_by_ao){
            return true;
        }

        if($user->is_dda && !$this->process->verified_by_dda && $this->process->verified_by_ao){
            return true;
        }
        if($user->is_jda && !$this->process->verified_by_jda && $this->process->verified_by_dda){
            return true;
        }
        if($user->is_adaa && !$this->process->verified_by_adaa && $this->process->verified_by_jda){
            return true;
        }
     
        return false;
    }

    public function getGenerateFormA2Attribute(){

        $user = request()->user;
        if(empty($user)){
            return false;
        }

        if($this->form_a2_id){
            return false;
        }

        if($user->is_adaa && $this->process->verified_by_adaa){
            return true;
        }
     
        return false;

    }
    

}

app/Http/Controllers/FormA1Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Forms\FormA1;
use App\Http\Requests\Forms\FormA1Request;
use Illuminate\Support\Str;
use App\Models\Forms\FormA1Process;

class FormA1Controller extends Controller
{
    public function list(Request $request){
        $user = $request->user;
        $can_process_form_a1 = $user->can_process_form_a1;
        $can_apply_form_a1 = $user->can_apply_form_a1;
        $forms = [];
        if($can_apply_form_a1 || $can_process_form_a1){
            $forms = FormD::orderBy('updated_at', 'desc')
                                ->when($can_apply_form_d, function($query) use($user){
                                    return $query->where('created_by', $user->id);
                                })->get();
        }
        return view('form-a1.list')->withForms($forms);
    }
   
    public function view($uuid, Request $request){
        $form = FormA1::where('uuid', $uuid)
        ->first();
        if(!$form->can_view){
            return redirect()->to('404');
        }
        return view('form-a1.view')->withForm($form);

    }
    
    public function create(){
        return view('form-a1.form');
    }

    public function edit($uuid, Request $request){
        $form = FormA1::where('uuid', $uuid)
                ->where('created_by', $request->user->id)
                ->where('edit_required', 1)
                ->first();
        if(empty($form)){
            return redirect()->to('404');
        }
        return view('form-a1.form')->withForm($form);
    }

    public function store(FormA1Request $request){

        $validated = (object) $request->validated();

        $row = FormA1::where('uuid', $validated->uuid)->first();

        if(empty($row)){
            $row = new FormA1;
            $row->created_by = $request->user->id;
            $row->uuid = Str::uuid();
        } 

        $row->name = $validated->name;
        $row->concern = $validated->concern;
        $row->address = $validated->address;
        $row->telephone = $validated->telephone;
        $row->saleAddress = $validated->saleAddress;
        $row->storageAddress = $validated->storageAddress;
        $row->fertilizerName = $validated->fertilizerName;
        $row->certifiateSource = $validated->certifiateSource;
        $row->fertilizerName1 = $validated->fertilizerName1;
        $row->certifiateSource1 = $validated->certifiateSource1;
        $row->renewal = $validated->renewal;
        $row->documents = $validated->documents;
        $row->relevantInfo = $validated->relevantInfo;
        $row->application_place = $validated->application_place;
        $row->date = $validated->date;
        $row->signature = $validated->signature;
        $row->place = $validated->place;
        $row->signature1 = $validated->signature1;
        $row->updated_by = $request->user->id;
        $row->edit_required = 0;
        $row->save();

        $process = new FormA1Process;
        $process->form_a1_id = $row->id;
        $process->save();

        $url = url('/dashboard');

        return response()->json(['redirect' => $url]);
    }
}

resources/views/form-a1/dashboard.blade.php
<div class="card">
    <div class="card-body">
    <h4 class="text-center">Form A1</h4>
        <a href="{{url('form-a1')}}" class="text-center w-100 d-block">{{$forms->forma1}}</a>
    </div>
</div>

resources/views/form-a1/list.blade.php
@extends('layouts.form-a1')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5>Form A1</h5>
                    @include('form-a1.table')
                </div>
            </div>

        </div>
    </div>
</div>



@endsection

resources/views/form-a1/table.blade.php
<table class="table table-bordered">
    <thead>
        <tr>
            <th>UUID</th>
            <th>AO</th>
            <th>DDA</th>
            <th>JDA</th>
            <th>ADA (Authority)</th>
        </tr>
    </thead>
    <tbody ng-cloak>
        @foreach($forms as $form)
            <tr>
                <td>
                    <div>
                    @if($form->can_edit)
                        <a href="{{url('form-a1/'.$form->uuid.'/edit')}}" class="text-danger mr-2" target="_blank">Edit Form</a>
                    @endif
                   
                    
                    <a href="{{url('form-a1/'.$form->uuid)}}" target="_blank">View / Print Form</a>
                   
                    @if($form->generate_form_a2)
                        <a href="{{url('form-a1/'.$form->uuid.'/form-a2')}}" class="ml-4 text-danger mr-2" target="_blank">Generate Form A2</a>
                    @endif
                    @if($form->form_a2_id )
                        <a href="{{url('form-a1/'.$form->uuid.'/form-a2/view')}}" class="ml-4 text-danger mr-2" target="_blank">Download Form A2</a>
                    @endif
                    </div>
                    <div>
                        <small>{{$form->updated_at}}</small>
                    </div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_ao , 'reject_reason' => $form->process->rejected_by_ao])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_dda , 'reject_reason' => $form->process->rejected_by_dda])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_jda , 'reject_reason' => $form->process->rejected_by_jda])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_adaa , 'reject_reason' => $form->process->rejected_by_adaa])</div>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/form-a1/view.blade.php
@extends('layouts.view')

@section('action')

@include('shared.form.action', ['type' => 'form-a1'])

@endsection

@section('content')

@include('form-a1.shared.view-title')

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <p>1. Details Of the Applicant</p>
                <p>a. Name Of the Applicant : {{$form->name}}</p>
            </div>
        </div>
    </div>
</div>

@endsection