routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\LoginController@view');
Route::get('/logout', 'User\LoginController@logout');
Route::get('dashboard', 'DashboardController@view');
Route::get('forms', 'FormsController@view');

Route::group(['prefix' => 'form-d'], function(){
    Route::get('', 'FormDController@list');
    Route::get('create', 'FormDController@create');
    Route::get('{uuid}/edit', 'FormDController@edit');
    Route::get('{uuid}', 'FormDController@view');
    Route::get('{uuid}/form-f', 'FormFController@create');
    Route::get('{uuid}/form-f/view', 'FormFController@view');

});

Route::group(['prefix' => 'form-ii'], function(){
    Route::get('', 'FormIIController@list');
    Route::get('create', 'FormIIController@create');
    Route::get('{uuid}/edit', 'FormIIController@edit');
    Route::get('{uuid}', 'FormIIController@view');
    Route::get('{uuid}/form-iii', 'FormIIIController@create');
    Route::get('{uuid}/form-iii/view', 'FormIIIController@view');

});

Route::group(['prefix' => 'form-a1'], function(){
    Route::get('', 'FormA1Controller@list');
    Route::get('create', 'FormA1Controller@create');
    Route::get('{uuid}/edit', 'FormA1Controller@edit');
    Route::get('{uuid}', 'FormA1Controller@view');
    Route::get('{uuid}/form-a2', 'FormA2Controller@create');
    Route::get('{uuid}/form-a2/view', 'FormA2Controller@view');

});

app/Models/Forms/FormII.php
<?php

namespace App\Models\Forms;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormII extends Model
{
    protected $table = 'form_ii';

    protected $fillable = [];

    protected $hidden = ['id', 'created_at', 'updated_at', 'deleted_at', 'created_by', 'updated_by', 'deleted_by'];
    
    protected $casts = ['documents' => 'object', 'edit_required' => 'boolean'];

    public function formiii(){
        return $this->hasOne('App\Models\Forms\FormIII', 'id', 'form_iii_id');
    }

    public function getCanViewAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if($this->created_by === $user->id){
            return true;
        }
        if($user->can_process_form_ii){
            return true;
        }
        return false;
    }

    public function getCanEditAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if(!$this->edit_required){
            return false;
        }

        return $this->created_by  === $user->id;
    }

    public function owner(){
        return $this->hasOne('App\Models\User', 'id', 'created_by');
    }

    public function process(){
        return $this->hasOne('App\Models\Forms\FormIIProcess', 'form_ii_id', 'id')->orderBy('id', 'desc');
    }

    public function getCanProcessAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if(!$user->can_process_form_ii){
            return false;
        }
        if($this->can_edit){
            return false;
        }
        if($this->form_iii_id){
            return false;
        }
        if($user->is_aoqc && !$this->process->verified_by_aoqc){
            return true;
        }

        if($user->is_dda && !$this->process->verified_by_dda && $this->process->verified_by_aoqc){
            return true;
        }
        if($user->is_jda && !$this->process->verified_by_jda && $this->process->verified_by_dda){
            return true;
        }
        if($user->is_ada && !$this->process->verified_by_ada && $this->process->verified_by_jda){
            return true;
        }
     
        if($user->is_director && !$this->process->verified_by_director && $this->process->verified_by_ada){
            return true;
        }
     
        return false;
    }

    public function getGenerateFormIIIAttribute(){

        $user = request()->user;
        if(empty($user)){
            return false;
        }

        if($this->form_iii_id){
            return false;
        }

        if($user->is_director && $this->process->verified_by_director){
            return true;
        }
     
        return false;

    }


}

app/Http/Controllers/FormIIController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Forms\FormII;
use App\Http\Requests\Forms\FormIIRequest;
use Illuminate\Support\Str;
use App\Models\Forms\FormIIProcess;


class FormIIController extends Controller
{
    public function list(Request $request){
        $user = $request->user;
        $can_process_form_ii = $user->can_process_form_ii;
        $can_apply_form_ii = $user->can_apply_form_ii;
        $forms = [];
        if($can_apply_form_ii || $can_process_form_ii){
            $forms = FormII::orderBy('updated_at', 'desc')
                                ->when($can_apply_form_ii, function($query) use($user){
                                    return $query->where('created_by', $user->id);
                                })->get();
        }
        return view('form-ii.list')->withForms($forms);
    }

    public function view($uuid, Request $request){
        $form = FormII::where('uuid', $uuid)
        ->first();
        if(!$form->can_view){
            return redirect()->to('404');
        }
        return view('form-ii.view')->withForm($form);

    }

    public function create(){
        return view('form-ii.form');
    }

    public function edit($uuid, Request $request){
        $form = FormII::where('uuid', $uuid)
                ->where('created_by', $request->user->id)
                ->where('edit_required', 1)
                ->first();
        if(empty($form)){
            return redirect()->to('404');
        }
        return view('form-ii.form')->withForm($form);
    }

    public function store(FormIIRequest $request){

        $validated = (object) $request->validated();

        $row = FormII::where('uuid', $validated->uuid)->first();

        if(empty($row)){
            $row = new FormII;
            $row->created_by = $request->user->id;
            $row->uuid = Str::uuid();
        } 
        $row->applicantphoto = $validated->applicantphoto;
        $row->name = $validated->name;
        $row->address = $validated->address;
        $row->email = $validated->email;
        $row->premisesAddress = $validated->premisesAddress;
        $row->validity = $validated->validity;
        $row->storeAddress = $validated->storeAddress;
        $row->pestControl = $validated->pestControl;
        $row->residentArea = $validated->residentArea;
        $row->foodArticle = $validated->foodArticle;
        $row->insecticideQualification = $validated->insecticideQualification;
        $row->courseName = $validated->courseName;
        $row->durationCourse = $validated->durationCourse;
        $row->certificateAward = $validated->certificateAward;
        $row->manufactureDetails = $validated->manufactureDetails;
        $row->commercialApplication = $validated->commercialApplication;
        $row->zonalBranchAddress = $validated->zonalBranchAddress;
        $row->premisesLicenceAddress = $validated->premisesLicenceAddress;
        $row->technicalExpertise = $validated->technicalExpertise;
        $row->refApprovalNumber = $validated->refApprovalNumber;
        $row->itsIssueDate = $validated->itsIssueDate;
        $row->itsValidityDate = $validated->itsValidityDate;
        $row->nameRestrict = $validated->nameRestrict;
        $row->techPersonName = $validated->techPersonName;
        $row->insecticideRestrict = $validated->insecticideRestrict;
        $row->particularsQuantity = $validated->particularsQuantity;
        $row->detailsEquipment = $validated->detailsEquipment;
        $row->particularLicence = $validated->particularLicence;
        $row->otherStateApplicant = $validated->otherStateApplicant;
        $row->stateLicenceNumber = $validated->stateLicenceNumber;
        $row->grantDate = $validated->grantDate;
        $row->ApplicationFee = $validated->ApplicationFee;
        $row->documents = $validated->documents;
        $row->relevantInfo = $validated->relevantInfo;
        $row->signature = $validated->signature;
        $row->decName = $validated->decName;
        $row->sonOfname = $validated->sonOfname;
        $row->capacityAs = $validated->capacityAs;
        $row->virtueOf = $validated->virtueOf;
        $row->application_place = $validated->application_place;
        $row->date = $validated->date;
        $row->signature1 = $validated->signature1;
        $row->updated_by = $request->user->id;
        $row->edit_required = 0;
        $row->save();

        $process = new FormIIProcess;
        $process->form_ii_id = $row->id;
        $process->save();

        $url = url('/dashboard');

        return response()->json(['redirect' => $url]);
    }

}

resources/views/form-ii/dashboard.blade.php
<div class="card">
    <div class="card-body">
    <h4 class="text-center">Form II</h4>
        <a href="{{url('form-ii')}}" class="text-center w-100 d-block">{{$forms->formii}}</a>
    </div>
</div>

resources/views/form-ii/list.blade.php
@extends('layouts.form-d')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
            <h5>Form II</h5>
        @include('form-ii.table')
            </div>
        </div>
       
        </div>
    </div>
</div>



@endsection

resources/views/form-ii/table.blade.php
<table class="table table-bordered">
    <thead>
        <tr>
            <th>UUID</th>
            <th>AO(QCI)</th>
            <th>DDA</th>
            <th>JDA</th>
            <th>ADA</th>
            <th>Director</th>
        </tr>
    </thead>
    <tbody ng-cloak>
        {@foreach($forms as $form)
            <tr>
                <td>
                    <div>
                    @if($form->can_edit)
                        <a href="{{url('form-ii/'.$form->uuid.'/edit')}}" class="text-danger mr-2" target="_blank">Edit Form</a>
                    @endif
                   
                    
                    <a href="{{url('form-ii/'.$form->uuid)}}" target="_blank">View / Print Form</a>
                   
                    @if($form->generate_form_iii)
                        <a href="{{url('form-ii/'.$form->uuid.'/form-iii')}}" class="ml-4 text-danger mr-2" target="_blank">Generate Form III</a>
                    @endif
                    @if($form->form_iii_id )
                        <a href="{{url('form-ii/'.$form->uuid.'/form-iii/view')}}" class="ml-4 text-danger mr-2" target="_blank">Download Form III</a>
                    @endif
                    </div>
                    <div>
                        <small>{{$form->updated_at}}</small>
                    </div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_aoqc , 'reject_reason' => $form->process->rejected_by_aoqc])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_dda , 'reject_reason' => $form->process->rejected_by_dda])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_jda , 'reject_reason' => $form->process->rejected_by_jda])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_ada , 'reject_reason' => $form->process->rejected_by_ada])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_director , 'reject_reason' => $form->process->rejected_by_director])</div>
                
                </td>
            </tr>
        @endforeach
}    </tbody>
</table>

resources/views/form-ii/view.blade.php
@extends('layouts.view')

@section('action')

@include('shared.form.action', ['type' => 'form-ii'])

@endsection

@section('content')

@include('form-ii.shared.view-title')
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <p>To</p>
                    <p>The Licensing Authority, <br>
                        Department Of Agriculture & Farmers welfare, <br>
                        Puducherry.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <p>Name, address and e-mail address of the applicant</p>
                </div>
                <div class="col-sm-6 col-md-6">
                    <p>{{$form->name}}, <br>{{$form->address}}, <br>{{$form->email}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <p>2. Whether the application is for</p>
                </div>
                <div class="col-sm-6 col-md-6">
                    <strong>{{strtoupper(session()->get('user')->role->name)}}</strong>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection