routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\LoginController@view');
Route::get('/logout', 'User\LoginController@logout');
Route::get('dashboard', 'DashboardController@view');
Route::get('forms', 'FormsController@view');

Route::group(['prefix' => 'form-d'], function(){
    Route::get('', 'FormDController@list');
    Route::get('create', 'FormDController@create');
    Route::get('{uuid}/edit', 'FormDController@edit');
    Route::get('{uuid}', 'FormDController@view');
    Route::get('{uuid}/form-f', 'FormFController@create');
    Route::get('{uuid}/form-f/view', 'FormFController@view');

});

Route::group(['prefix' => 'form-ii'], function(){
    Route::get('', 'FormIIController@list');
    Route::get('create', 'FormIIController@create');
    Route::get('{uuid}/edit', 'FormIIController@edit');
    Route::get('{uuid}', 'FormIIController@view');
    Route::get('{uuid}/form-iii', 'FormIIIController@create');
    Route::get('{uuid}/form-iii/view', 'FormIIIController@view');

});

Route::group(['prefix' => 'form-a1'], function(){
    Route::get('', 'FormA1Controller@list');
    Route::get('create', 'FormA1Controller@create');
    Route::get('{uuid}/edit', 'FormA1Controller@edit');
    Route::get('{uuid}', 'FormA1Controller@view');
    Route::get('{uuid}/form-a2', 'FormA2Controller@create');
    Route::get('{uuid}/form-a2/view', 'FormA2Controller@view');

});

app/Models/Forms/FormD.php
<?php

namespace App\Models\Forms;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormD extends Model
{
    use SoftDeletes;

    protected $table = 'form_d';

    protected $fillable = [];

    protected $hidden = ['id', 'created_at', 'updated_at', 'deleted_at', 'created_by', 'updated_by', 'deleted_by'];
    
    protected $casts = ['documents' => 'object', 'edit_required' => 'boolean'];

    public function formf(){
        return $this->hasOne('App\Models\Forms\FormF', 'id', 'form_f_id');
    }

    public function getCanViewAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if($this->created_by === $user->id){
            return true;
        }
        if($user->can_process_form_d){
            return true;
        }
        return false;
    }

    public function getCanEditAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if(!$this->edit_required){
            return false;
        }

        return $this->created_by  === $user->id;
    }



   
    public function owner(){
        return $this->hasOne('App\Models\User', 'id', 'created_by');
    }

    public function process(){
        return $this->hasOne('App\Models\Forms\FormDProcess', 'form_d_id', 'id')->orderBy('id', 'desc');
    }

    public function getCanProcessAttribute(){
        $user = request()->user;
        if(empty($user)){
            return false;
        }
        if(!$user->can_process_form_d){
            return false;
        }
        if($this->can_edit){
            return false;
        }
        if($this->form_f_id){
            return false;
        }
        if($user->is_ao && !$this->process->verified_by_ao){
            return true;
        }

        if($user->is_dda && !$this->process->verified_by_dda && $this->process->verified_by_ao){
            return true;
        }
        if($user->is_jda && !$this->process->verified_by_jda && $this->process->verified_by_dda){
            return true;
        }
        if($user->is_ada && !$this->process->verified_by_ada && $this->process->verified_by_jda){
            return true;
        }
     
        if($user->is_director && !$this->process->verified_by_director && $this->process->verified_by_ada){
            return true;
        }
     
        return false;
    }

    public function getGenerateFormFAttribute(){

        $user = request()->user;
        if(empty($user)){
            return false;
        }

        if($this->form_f_id){
            return false;
        }

        if($user->is_director && $this->process->verified_by_director){
            return true;
        }
     
        return false;

    }
    
}

app/Http/Controllers/FormDController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Forms\FormD;
use App\Http\Requests\Forms\FormDRequest;
use Illuminate\Support\Str;
use App\Models\Forms\FormDProcess;


class FormDController extends Controller
{
    public function list(Request $request){
        $user = $request->user;
        $can_process_form_d = $user->can_process_form_d;
        $can_apply_form_d = $user->can_apply_form_d;
        $forms = [];
        if($can_apply_form_d || $can_process_form_d){
            $forms = FormD::orderBy('updated_at', 'desc')
                                ->when($can_apply_form_d, function($query) use($user){
                                    return $query->where('created_by', $user->id);
                                })->get();
        }
        return view('form-d.list')->withForms($forms);
    }
   
    public function view($uuid, Request $request){
        $form = FormD::where('uuid', $uuid)
        ->first();
        if(!$form->can_view){
            return redirect()->to('404');
        }
        return view('form-d.view')->withForm($form);

    }
    
    public function create(){
        return view('form-d.form');
    }

    public function edit($uuid, Request $request){
        $form = FormD::where('uuid', $uuid)
                ->where('created_by', $request->user->id)
                ->where('edit_required', 1)
                ->first();
        if(empty($form)){
            return redirect()->to('404');
        }
        return view('form-d.form')->withForm($form);
    }

  

    public function store(FormDRequest $request){

        $validated = (object) $request->validated();

        $row = FormD::where('uuid', $validated->uuid)->first();

        if(empty($row)){
            $row = new FormD;
            $row->created_by = $request->user->id;
            $row->uuid = Str::uuid();
        } 

        $row->name = $validated->name;
        $row->address = $validated->address;
        $row->concern = $validated->concern;
        $row->qualification = $validated->qualification;
        $row->new_comer = $validated->new_comer;
        $row->premises = $validated->premises;
        $row->particulars = $validated->particulars;
        $row->certificates = $validated->certificates;
        $row->duration = $validated->duration;
        $row->quantity = $validated->quantity;
        $row->business = $validated->business;
        $row->quantities = $validated->quantities;
        $row->renewal = $validated->renewal;
        $row->requiring = $validated->requiring;
        $row->documents = $validated->documents;
        $row->applicant_name = $validated->applicant_name;
        $row->applicant_address = $validated->applicant_address;
        $row->application_place = $validated->application_place;
        $row->date = $validated->date;
        $row->signature = $validated->signature;
        $row->updated_by = $request->user->id;
        $row->edit_required = 0;
        $row->save();

        $process = new FormDProcess;
        $process->form_d_id = $row->id;
        $process->save();

        $url = url('/dashboard');

        return response()->json(['redirect' => $url]);
    }

}

resources/views/form-d/dashboard.blade.php
<div class="card">
    <div class="card-body">
    <h4 class="text-center">Form D</h4>
        <a href="{{url('form-d')}}" class="text-center w-100 d-block">{{$forms->formd}}</a>
    </div>
</div>

resources/views/form-d/list.blade.php
@extends('layouts.form-d')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
            <h5>Form D</h5>
        @include('form-d.table')
            </div>
        </div>
       
        </div>
    </div>
</div>



@endsection

resources/views/form-d/table.blade.php
<table class="table table-bordered">
    <thead>
        <tr>
            <th>UUID</th>
            <th>AO</th>
            <th>DDA</th>
            <th>JDA</th>
            <th>ADA</th>
            <th>Director</th>
        </tr>
    </thead>
    <tbody ng-cloak>
        @foreach($forms as $form)
            <tr>
                <td>
                    <div>
                    @if($form->can_edit)
                        <a href="{{url('form-d/'.$form->uuid.'/edit')}}" class="text-danger mr-2" target="_blank">Edit Form</a>
                    @endif
                   
                    
                    <a href="{{url('form-d/'.$form->uuid)}}" target="_blank">View / Print Form</a>
                   
                    @if($form->generate_form_f)
                        <a href="{{url('form-d/'.$form->uuid.'/form-f')}}" class="ml-4 text-danger mr-2" target="_blank">Generate Form F</a>
                    @endif
                    @if($form->form_f_id )
                        <a href="{{url('form-d/'.$form->uuid.'/form-f/view')}}" class="ml-4 text-danger mr-2" target="_blank">Download Form F</a>
                    @endif
                    </div>
                    <div>
                        <small>{{$form->updated_at}}</small>
                    </div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_ao , 'reject_reason' => $form->process->rejected_by_ao])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_dda , 'reject_reason' => $form->process->rejected_by_dda])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_jda , 'reject_reason' => $form->process->rejected_by_jda])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_ada , 'reject_reason' => $form->process->rejected_by_ada])</div>
                </td>
                <td>
                  <div>@include('shared.form.status', ['verified_at' =>$form->process->verified_by_director , 'reject_reason' => $form->process->rejected_by_director])</div>
                
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/form-d/view.blade.php
@extends('layouts.view')

@section('action')

@include('shared.form.action', ['type' => 'form-d'])

@endsection

@section('content')

@include('form-d.shared.view-title')
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <p>To</p>
                    <p>The Registering Authority, <br>
                        Department Of Agriculture & Farmers welfare, <br>
                        Puducherry.
                    </p>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 1. Full name address of the applicant.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div><span>{{$form->name}}</span>, <br>{{$form->address}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> Name of the concern.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->concern}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 2. Does the applicant possess the qualification prescribed by the
                    State Government under Sub-clause (I) of clause 14 of the Fertilizer (Control) Order, 1985:
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->qualification}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 3. Is the applicant a new comer?
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->new_comer}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 4. Situation of the applicant’s premises where
                    {{strtolower($form->owner->role->name)}}
                    will be prepared.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->premises}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 5. Full particulars regarding specifications of
                    the {{strtolower($form->owner->role->name)}} for which the
                    certificate is required and the raw materials used in making the mixture.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->particulars}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 6. Full particulars of any other certificate of
                    manufacture, if any, issued by any other Registering Authority.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->certificates}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 7. How long has the applicant been carrying on the business of
                    preparing {{strtolower($form->owner->role->name)}}?
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->duration}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 8. Quantities of {{strtolower($form->owner->role->name)}} (in tonnes)
                    in my/out possession on the date of the Application and field at different addresses noted against
                    each.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->quantity}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 9. a) If the applicant has been carrying on the business of preparing
                    {{strtolower($form->owner->role->name)}}, give all particulars of such Mixtures handled, the period
                    and the place(s) at which the mixing of Fertilizers was done.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->business}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 9. b) Also give the quantities of
                    {{strtolower($form->owner->role->name)}}, handled during
                    the past Calendar year
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->quantities}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 10. If the application is for renewal, indicate
                    briefly why the original certificate could not be acted on within the period of its
                    validity.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->renewal}}</div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-12 col-md-6"> 11. Name and address of the person requiring
                    the special mixture of fertilizers.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->requiring}}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <h4>Documents</h4>
                    @foreach($form->documents as $document)
                    <a href="{{$document->url}}">{{$document->filename}}</a>
                    @endforeach
                </div>
            </div>
            @include('form-d.shared.declaration')
            <div class="row">
                <label class="col-sm-12 col-md-6"> Name and address of applicant.
                </label>
                <div class="col-sm-12 col-md-6">
                    <div>{{$form->applicant_name}}, <br>{{$form->applicant_address}}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div><strong>Place: </strong>{{$form->application_place}}</div>
                </div>
                <div class="col-sm-12">
                    <div><strong>Date: </strong>{{$form->date}}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="float-right">
                        {{$form->signature}}
                        <!-- <img src="{{$form->signature}}" alt=""> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection